# Change the default $TERM to tmux-256color
set -ga terminal-overrides ",xterm-256color:Tc"
set -g default-terminal "tmux-256color"
set -g mouse on

set -g extended-keys on
set -g extended-keys-format csi-u

# No bells at all
set -g bell-action none

# Change the prefix key to Meh-k
# unbind C-b

unbind C-b
set -g prefix M-a
bind M-a send-prefix

# Set default shell to fish, for both Linux and macOS
if-shell -b "uname | grep -q Linux" {
  set -g default-command /usr/bin/fish
  set-option -g default-shell /usr/bin/fish
}

if-shell -b "uname | grep -q Darwin" {
  set-option -g default-shell /opt/homebrew/bin/fish
}

# Start windows and panes at 1, not 0, as it is more reachable on keyboards
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# add plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind 's' split-window -v -c "#{pane_current_path}"
bind 'v' split-window -h -c "#{pane_current_path}"

run '~/.config/tmux/plugins/tpm/tpm'

run ~/.config/tmux/plugins/catppuccin/catppuccin.tmux

# set the theme to catppuccin
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "rounded"

set -g @catppuccin_window_left_separator "█"
set -g @catppuccin_window_middle_separator "█"
set -g @catppuccin_window_right_separator "█"

set -gF window-status-format "##I ##W"

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""

set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_date_time}"


bind-key "k" run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""

bind-key "o" display-popup -E -w 80% -h 70% -d '#{pane_current_path}' -T 'Sesh' tv sesh
bind-key "w" run-shell "sesh window \"$(sesh window | fzf-tmux -p 60%,50% --prompt '🪟  ')\""
bind -N "last-session (via sesh) " L run-shell "sesh last"
