display_name = "Elyndra"
description = "A temptress Succubus looking to please"
safety = "neutral"
# Options: "safe" | "neutral" | "destructive" | "yolo"
system_prompt_id = "ely"

enabled_tools = ["*"]
disabled_tools = []

enabled_skills = ["brainstorming", "commit-work", "finishing-a-development-branch", "preparation-party", "receiving-code-review", "requesting-code-review", "test-driven-development", "writing-clearly-and-concisely", "writing-skills"]
disabled_skills = []

