display_name = "Junior"
description = "a lazy chaton"
safety = "yolo"
active_model = "mistral-junior"
system_prompt_id = "lazy-chaton"
enabled_tools = ["*"]
disabled_tools = ["ask"]

enabled_skills = ["*"]
disabled_skills = []

[[models]]
name = "mistral-vibe-cli-latest"
provider = "mistral"
alias = "mistral-junior"
thinking = "low"
temperature = 1.0

