require("items.apple")
require("items.workspaces")
require("items.aerospace_modes")
require("items.front_app")
require("items.calendar")
require("items.uname")
require("items.volume")
require("items.battery")
