#!/usr/bin/env bash
# Shared helpers for the dotfiles installer. Sourced, never executed directly.

if (( BASH_VERSINFO[0] < 4 )); then
  echo "Error: this installer needs bash >= 4 (found ${BASH_VERSION})." >&2
  echo "On macOS: brew install bash, then re-run with that bash on PATH." >&2
  exit 1
fi

declare -gA STATE_COMPONENTS=()
declare -gA STATE_PACKAGES=()
STATE_PLATFORM=""

# Catppuccin Mocha palette (https://catppuccin.com/palette), used to theme
# gum's UI. Override any of these (or INSTALLER_ACCENT_COLOR) by exporting
# before running install.sh, e.g.:
#   INSTALLER_ACCENT_COLOR='#04B575' ./install.sh
: "${MOCHA_ROSEWATER:=#f5e0dc}"
: "${MOCHA_TEAL:=#94e2d5}"
: "${MOCHA_GREEN:=#a6e3a1}"
: "${MOCHA_YELLOW:=#f9e2af}"
: "${MOCHA_RED:=#f38ba8}"
: "${MOCHA_BLUE:=#89b4fa}"
: "${MOCHA_TEXT:=#cdd6f4}"
: "${MOCHA_SUBTEXT0:=#a6adc8}"
: "${MOCHA_CRUST:=#11111b}"

# Accent color for gum UI chrome (borders, highlights, selections).
: "${INSTALLER_ACCENT_COLOR:=$MOCHA_TEAL}"
: "${INSTALLER_INFO_COLOR:=$MOCHA_BLUE}"
: "${INSTALLER_WARN_COLOR:=$MOCHA_YELLOW}"
: "${INSTALLER_ERROR_COLOR:=$MOCHA_RED}"
: "${INSTALLER_TEXT_COLOR:=$MOCHA_TEXT}"
: "${INSTALLER_SUBTEXT_COLOR:=$MOCHA_SUBTEXT0}"

# gum's Ctrl+C/Esc exit codes (stable since gum 0.14, see
# charmbracelet/gum#771): Ctrl+C is always 130. Esc is 1 for `choose`
# (unambiguous there — no other reason to exit 1). For `confirm`, gum gives
# Esc and a literal "No" answer the same exit code (1), so we can't tell
# them apart; check_cancel treats a plain 1 as "answered no / skip" and only
# treats 130 as "abort the whole installer".
GUM_EXIT_INTERRUPT=130

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Error: '$1' is required but not found in PATH." >&2
    [[ -n "${2:-}" ]] && echo "  $2" >&2
    exit 1
  fi
}

log_info() {
  gum log --level info \
    --level.foreground "$INSTALLER_INFO_COLOR" \
    --message.foreground "$INSTALLER_TEXT_COLOR" "$1"
}
log_warn() {
  gum log --level warn \
    --level.foreground "$INSTALLER_WARN_COLOR" \
    --message.foreground "$INSTALLER_TEXT_COLOR" "$1"
}
log_err() {
  gum log --level error \
    --level.foreground "$INSTALLER_ERROR_COLOR" \
    --message.foreground "$INSTALLER_TEXT_COLOR" "$1"
}

detect_platform() {
  case "$(uname -s)" in
    Darwin) echo "macOS" ;;
    Linux) echo "archlinux" ;;
    *)
      echo "Error: unsupported platform '$(uname -s)'." >&2
      exit 1
      ;;
  esac
}

state_dir() { echo "${XDG_STATE_HOME:-$HOME/.local/state}/dotfiles"; }
state_path() { echo "$(state_dir)/state.sh"; }

state_load() {
  STATE_COMPONENTS=()
  STATE_PACKAGES=()
  STATE_PLATFORM=""
  local f
  f=$(state_path)
  if [[ -f "$f" ]]; then
    # shellcheck disable=SC1090
    source "$f"
  fi
}

_serialize_assoc() {
  local var_name="$1"
  local -n arr_ref="$1"
  local out="${var_name}=("
  local k
  for k in "${!arr_ref[@]}"; do
    out+=" [$(printf '%q' "$k")]=$(printf '%q' "${arr_ref[$k]}")"
  done
  out+=" )"
  printf '%s\n' "$out"
}

state_save() {
  local dir f
  dir=$(state_dir)
  mkdir -p "$dir"
  f=$(state_path)
  {
    echo "# Auto-generated by install.sh on $(date +%Y-%m-%dT%H:%M:%S%z). Do not edit by hand."
    echo "STATE_PLATFORM=$(printf '%q' "$STATE_PLATFORM")"
    _serialize_assoc STATE_COMPONENTS
    _serialize_assoc STATE_PACKAGES
  } >"$f"
}

state_clear() { rm -f "$(state_path)"; }

# Stable content hash of a directory: path+content, sorted for determinism.
hash_dir() {
  local dir="$1"
  find "$dir" -type f -print0 | sort -z | xargs -0 sha256sum | sha256sum | cut -d' ' -f1
}

# gum wrappers -----------------------------------------------------------

# gm_choose_multi <header> <item...> -> prints selected items, one per line.
# Exits with gum's own status (0 = confirmed, 1 = Esc, 130 = Ctrl+C) so
# callers can tell a real cancel apart from "confirmed with nothing picked".
#
# Cursor, selected and unselected rows each get their own color + prefix so
# the three states stay visually distinct at a glance (previously all three
# shared one accent color, which made checked vs. merely-highlighted rows
# indistinguishable).
gm_choose_multi() {
  local header="$1"
  shift
  gum choose --no-limit --height 20 \
    --cursor-prefix "❯ " --selected-prefix "✓ " --unselected-prefix "  " \
    --cursor.foreground "$INSTALLER_ACCENT_COLOR" \
    --header.foreground "$INSTALLER_ACCENT_COLOR" \
    --selected.foreground "$MOCHA_GREEN" \
    --item.foreground "$INSTALLER_SUBTEXT_COLOR" \
    --header "$header" "$@"
}

gm_confirm() {
  gum confirm \
    --prompt.foreground "$INSTALLER_ACCENT_COLOR" \
    --selected.background "$INSTALLER_ACCENT_COLOR" \
    --selected.foreground "$MOCHA_CRUST" \
    --unselected.foreground "$INSTALLER_SUBTEXT_COLOR" \
    --unselected.background "" \
    "$1"
}

# check_cancel <exit-code> [message] -> exits the whole installer if the
# code is Ctrl+C (130), saving whatever state was accumulated so far first.
# A plain 1 (Esc, or "No" on a confirm) is left for the caller to handle as
# a normal negative answer.
check_cancel() {
  local rc="$1" message="${2:-Cancelled.}"
  if [[ "$rc" -eq "$GUM_EXIT_INTERRUPT" ]]; then
    echo
    log_warn "$message"
    state_save
    exit "$GUM_EXIT_INTERRUPT"
  fi
}
