source 'https://rubygems.org'

# Standard gems
gem 'puma'
gem 'rails', '4.2.5.1'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

# Database gem
gem 'pg', '~> 0.15'

# SaSS and JS related
gem 'sass-rails', '~> 5.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'angular-rails-templates'

gem 'haml-rails', '~> 0.9.0'
# gem 'draper', '~> 2.1'
# gem 'cells', '~> 4.1', '>= 4.1.1'
# gem 'kaminari', '~> 0.16.3'

# auth
#gem 'devise'
#gem 'omniauth'
#gem 'grape_token_auth'

# API
gem 'grape'
gem 'grape-entity'
gem 'hashie-forbidden_attributes'
gem 'dotenv-rails'

# Background worker
#gem 'sidekiq'
#gem 'sidekiq-cron'
#gem 'sinatra', :require => nil
#gem 'redis'

group :production, :staging do
  gem 'rails_12factor'
  gem 'uglifier'
end

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'ffaker'

  #TDD and QA
  gem 'protractor-rails'
  gem 'jslint_on_rails'
  gem 'editorconfig', '~> 0.2.2'

  # Code review
  gem 'annotate'

  gem 'rubocop', require: false
  gem 'awesome_print', require:'ap'
end

group :test do
  gem 'database_cleaner'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'meta_request'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'pry-rails' # https://github.com/rweng/pry-rails
  gem 'quiet_assets'
  gem 'letter_opener'
end
