path+=(/usr/local/sbin)
. "$HOME/.config/cargo/env"
. "$HOME/.cargo/env"

path+=(/opt/homebrew/bin)

export HOMEBREW_PREFIX=/opt/homebrew
export HOMEBREW_CELLAR=/opt/homebrew/Cellar
export HOMEBREW_REPOSITORY=/opt/homebrew
export INFOPATH=/opt/homebrew/share/info: